services:
  mysql-order:
    # https://hub.docker.com/_/mysql
    image: mysql:8
    init: true
    restart: always
    user: "${DOCKER_UID}:${DOCKER_GID}"
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${DOCKER_MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${DOCKER_MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${DOCKER_MYSQL_USER}"
    ports:
      - "${DOCKER_MYSQL_3307}:3306"
    volumes:
      - "${DOCKER_DATA}/mysql:/var/lib/mysql:rw"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s
  redis-order:
    # https://hub.docker.com/_/redis
    # https://github.com/redis/redis/blob/7.0/redis.conf
    image: redis:7-alpine
    init: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "${DOCKER_REDIS_6380}:6379"
    volumes:
      - "${DOCKER_DATA}/redis:/data:rw"
      - ./docker/redis-dev/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s
